# syntax=container/dockerfile:1
FROM docker.io/nvidia/cuda:12.8.1-runtime-ubuntu24.04
ENV COMFYUI_DIR=/comfyui
ENV UV_PYTHON_INSTALL_DIR=/opt/python
ENV UV_LINK_MODE=copy
ENV VENV_PATH=/opt/python-venv
ENV WORKSPACE="/workspace"
ENV PYTHONPATH="${PYTHONPATH}:${PWD}"
ENV PATH="/root/.local/bin:${VENV_PATH}/bin:${PATH}"
ARG COMFYUI_TAG

RUN set -eux \
    && apt-get update \
    && apt-get full-upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends curl git aria2 ca-certificates parallel vim bash bash-completion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && uv venv -p 3.13 ${VENV_PATH} \
    && . ${VENV_PATH}/bin/activate

RUN set -eux \
    # ComfyUI をクローン,　依存関係をインストール
    && git clone https://github.com/comfyanonymous/ComfyUI.git ${COMFYUI_DIR} \
    && cd ${COMFYUI_DIR} \
    && if [ -z "${COMFYUI_TAG}" ]; then export COMFYUI_TAG="$(git describe --tags --abbrev=0)"; fi \
    && git checkout tags/${COMFYUI_TAG} \
    && uv pip install -r requirements.txt \
    && uv pip install -r manager_requirements.txt \
    && rm -rf /root/.cache/uv /root/.cache/pip /tmp/*

COPY . /container/
RUN set -eux \
    && chmod u+x /container/entrypoint.sh \
    && cp /container/extra_model_paths.yaml ${COMFYUI_DIR} \
    && uv pip uninstall pynvml \
    && uv pip install -U nvidia-ml-py \
    && rm -rf /root/.cache/uv /root/.cache/pip /tmp/*

# NVIDIAランタイムの設定
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_DISABLE_REQUIRE=1

ENV CLI_ARGS="--dont-print-server --enable-manager"

EXPOSE 8188 8888
WORKDIR ${COMFYUI_DIR}
ENTRYPOINT ["/container/entrypoint.sh"]
CMD ["python3", "-u", "main.py", "--listen", "--port", "8188", "${CLI_ARGS}"]
