# syntax=container/dockerfile:1
FROM docker.io/nvidia/cuda:12.8.1-runtime-ubuntu24.04
ENV COMFYUI_DIR=/comfyui
ENV UV_PYTHON_INSTALL_DIR=/opt/python
ENV VENV_PATH=/opt/python-venv
ENV WORKSPACE="/workspace"
ENV PYTHONPATH="${PYTHONPATH}:${PWD}"
ENV PATH="/root/.local/bin:${VENV_PATH}/bin:${PATH}"
ARG COMFYUI_TAG

RUN set -eux \
    && apt-get update \
    && apt-get full-upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends curl git aria2 ca-certificates parallel vim bash bash-completion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && uv venv -p 3.13 ${VENV_PATH} \
    && . ${VENV_PATH}/bin/activate \
    && ${WORKSPACE}/comfyui/{custom_nodes,scripts}

RUN set -eux \
    # ComfyUI をクローン,　依存関係をインストール
    && git clone https://github.com/comfyanonymous/ComfyUI.git ${COMFYUI_DIR} \
    && cd ${COMFYUI_DIR} \
    && if [ -z "${COMFYUI_TAG}" ]; then export COMFYUI_TAG="$(git describe --tags --abbrev=0)"; fi \
    && git checkout tags/${COMFYUI_TAG} \
    && uv pip install -r requirements.txt

RUN set -eux \
    # ComfyUI-Impact-Pack ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b Main --depth 1 https://github.com/ltdrdata/ComfyUI-Impact-Pack.git comfyui-impact-pack \
    && cd comfyui-impact-pack \
    && uv pip install -r requirements.txt

RUN set -eux \
    # rgthree-comfy ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b main --depth 1 https://github.com/rgthree/rgthree-comfy.git rgthree-comfy \
    && cd rgthree-comfy \
    && uv pip install -r requirements.txt

RUN set -eux \
    # comfyui-crystools ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b main --depth 1 https://github.com/crystian/comfyui-crystools.git comfyui-crystools \
    && cd comfyui-crystools \
    && uv pip install -r requirements.txt

RUN set -eux \
    # ComfyUI-Custom-Scripts ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b main --depth 1 https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git comfyui-custom-scripts

RUN set -eux \
    # ComfyUI-Autocomplete-Plus ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b main --depth 1 https://github.com/newtextdoc1111/ComfyUI-Autocomplete-Plus.git comfyui-autocomplete-plus

RUN set -eux \
    # ComfyUI-ppm ノードをインストール
    && cd ${WORKSPACE}/comfyui/custom_nodes \
    && git clone -b master --depth 1 https://github.com/pamparamm/ComfyUI-ppm.git comfyui-ppm

WORKDIR ${COMFYUI_DIR}

COPY . /container/
RUN set -eux \
    && chmod u+x /container/entrypoint.sh \
    && cp /container/extra_model_paths.yaml ${COMFYUI_DIR} \
    && mkdir -p ${COMFYUI_DIR}/custom_nodes/ \
    && mv /container/*.py ${COMFYUI_DIR}/custom_nodes/ \
    && chmod a+x ${COMFYUI_DIR}/custom_nodes/*.py \
    && uv pip uninstall pynvml \
    && uv pip install -U nvidia-ml-py

# NVIDIAランタイムの設定
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_DISABLE_REQUIRE=1

ENV CLI_ARGS="--dont-print-server --enable-manager"

EXPOSE 8188 8888
ENTRYPOINT ["/container/entrypoint.sh"]
CMD python3 -u main.py --listen --port 8188 ${CLI_ARGS}
